### ISSUE TITLE
termbox isn't maintained anymore and is causing a panic error

### ISSUE THREAD

**Issue by redianthus** [tigrawap/slit#84]
Hi,

When running `slit` on any file with a recent alacritty:

```
panic: termbox: error while reading terminfo data: termbox: unsupported terminal

goroutine 1 [running]:
github.com/tigrawap/slit.(*viewer).termGui(0xc00000c1e0)
	/home/zapashcanon/.local/bin/go/src/github.com/tigrawap/slit/term.go:478 +0xa14
github.com/tigrawap/slit.(*Slit).Display(0xc000072410)
	/home/zapashcanon/.local/bin/go/src/github.com/tigrawap/slit/slit.go:109 +0x12f
main.main()
	/home/zapashcanon/.local/bin/go/src/github.com/tigrawap/slit/cmd/slit/main.go:96 +0x5f2
```

See [this similar](https://github.com/gopasspw/gopass/issues/1264) issue for some workarounds. :-)

**Comment by tigrawap** [comment]
I don't mind switching to fork, but on my osx machine it works fine with alacrity, and I don't have linux desktop machine to test against alacrity on Linux

Could you try switching import to that fork and see if it solves the issue?

**Comment by redianthus** [comment]
It's on a recent alacritty (`alacritty 0.7.0-dev (4975be2)`) so that may be why you don't experience the error. I think it works on my other workstations with older alacritty.

Rather using the fork, switching to [tcell](https://github.com/gdamore/tcell) may be the way to go (that's what's suggested in my previous link) ?

I'll try to use the fork instead but I don't know Go so I don't know if I'll succeed, I'll let you know.
